<link rel="stylesheet" href="/js/slider/flexslider.css" type="text/css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
<script src="/js/slider/jquery.flexslider.js"></script>
<script src="/js/slider/jquery.flexslider-min.js"></script>

<script type="text/javascript" charset="utf-8">
    $(window).load(function() {
        $('.flexslider').flexslider({
            animation: 'slide'
    
        }
    );
    });
</script>


<div class="hero-unit" style="background:#009cff; height: 100px">
    <div class="span16">
        <h1>SGTi</h1>
        <p>Because we can</p>
    </div>  
</div>
<div class="row">
    <div class="span6 offset1">
        <div class="flexslider">
            <ul class="slides">
                <li>
                    <img src="/img/4.jpg" />
                    <p> Fotos tomadas en Maldonado</p>
                </li>
                <li>
                    <img src="/img/3.jpg" />
                </li>
                <li>
                    <img src="/img/2.jpg" />
                </li>
                 <li>
                    <img src="/img/5.jpg" />
                    <p> Fotos tomadas en Maldonado</p>
                </li>
            </ul>
        </div>
    </div>
    <div class="span7 offset1">
        <p>
            El Antiguo jefe de la ingeniería que sabía todos los detalles del trabajo y estaba en todas y cada una de las etapas de su cumplimiento logró verdaderas maravillas en su época mediante métodos puramente empíricos y los datos que le podrían suministrar sus manuales. Pero sus obras, indudablemente grandiosa, parecen sólo un juego de niños al lado de las emprendidas por los ingenieros científicos de hoy en día.

            Conformes el desarrollo de técnicas nuevas llevó a los ingeniero a la producción de aparatos de comunicación, computadoras, radares, armas nucleares, proyectiles teledirigidos, aviones supersónicos y naves espaciales controladas electrónicamente, el trabajo fue tan complejo que no fue posible que una sola persona comprendiera todas las partes de ningún aparato. El viejo concepto del jefe (una sola persona) fue sustituido por el conjunto llamado INGENIERO EN SISTEMAS. La ingeniería en sistemas entraña de la planeación y división del trabajo que son necesarias para realizar ordenadamente obras.

            A continuación la siguiente investigación se basa en todas los aspectos que cubre un ingeniero en sistemas computacionales, empezando desde su historia hasta lo que es en sí esta carrera tan interesante.
        </p>
    </div>
</div>
