<?php
include("tabBarDocentes.php");
include("dataTables.php");
?>

<script type="text/javascript" charset="utf-8">
    $(document).ready(function() {
        oAlumnosTable = $('#alumnos').dataTable({
            "bPaginate": true,
            //bLengthChange muestra un combo para seleccionar cuantas entradas se quieren mostrar en pantalla
            "bLengthChange": false,
            "bFilter": true,
            "bSort": true,
            "bInfo": true,
            "bAutoWidth": false,
            "aaSorting": [[ 1, "asc" ]],
            "sScrollY": "200px",
            "bPaginate": false,
            "oLanguage": {
                "sLengthMenu": "Mostrar _MENU_ filas por pagina",
                "sZeroRecords": "No hay registros",
                "sInfo": "Mostrando _START_ a _END_ de _TOTAL_ registros",
                "sInfoEmpty": "Mostrando 0 a 0 de 0 registros",
                "sInfoFiltered": "(filtered from _MAX_ total records)",
                "sSearch":"Buscar por:"
            },
            "aoColumns" : [
                { sWidth: '30%' },
                { sWidth: '30%' },
                { sWidth: '30%' },
                { sWidth: '20%' },
                { sWidth: '5%' },
                { bHidden: true }
            ] 
        });
        
        $('#curso-select').change(function() {
            // traigo la id del plan seleccionado
            var cursoId =  $("#curso-select").val();   
            
            updateAlumnosEventoCalTable(cursoId, oAlumnosTable);
        });
        
        $("#curso-select").trigger('change');
    });
</script>

<div class="row show-grid">
    <div class="span16 ">
        <div class="row show-grid">
            <div class="span8 offset1 ">
                <h2>Agregar Evento Calificacion</h2>
            </div> 
        </div> <!-- /clearfix -->

        <form action="#" method="post">
            <fieldset>
                <div class="row show-grid">
                    <div class="span4">
                        <div class="clearfix">
                            <label>Cursos:&nbsp;</label> 
                            <div class="input">
                                <select name="curso-select" id="curso-select">
                                    <?php if ($this->listaCursos != null) : ?>
                                        <?php foreach ($this->listaCursos as $curso) : ?>
                                            <option value="<?php echo $curso->getId(); ?>"><?php echo $curso->getMateria()->getNombre() . "-" . $curso->getAnio(); ?></option>
                                        <?php endforeach; ?>
                                    <?php endif; ?>

                                </select>
                            </div>
                        </div><!-- /clearfix -->
                    </div>

                </div>
                <div class="row">
                    <div class="span3">
                        <div class="clearfix">
                            <label for="tipoEvento">Tipo Evento:&nbsp;</label>
                            <div class="input">
                                <select name="tipoEvento" id="tipoEvento">
                                    <?php if ($this->listaTipos != null) : ?>
                                        <?php foreach ($this->listaTipos as $tipo) : ?>
                                            <option value="<?php echo $tipo->getId(); ?>"><?php echo $tipo->getNombre(); ?></option>
                                        <?php endforeach; ?>
                                    <?php endif; ?>
                                </select>
                            </div>
                        </div><!-- /clearfix -->
                    </div>

                    <div class="span2 offset3 ">
                        <div class=" clearfix">
                            <label>Nota Maxima:</label> 
                            <div class="input">
                                <input class="span1"  id="notaMax" name="notaMax" maxlength="3" type="text"/> 
                            </div>
                        </div> 
                    </div><!-- /clearfix -->

                    <div class="span2 offset1">
                        <div class=" clearfix">
                            <label>Nota Aprobacion:</label> 
                            <div class="input">
                                <input class="span1"  id="notaAprobacion" name="notaAprobacion" maxlength="3" type="text"/> 
                            </div>
                        </div><!-- /clearfix -->
                    </div>
                    <div class="span0">
                        <div class=" clearfix">
                            <label>Descripcion:</label> 
                            <div class="input">
                                <textarea class="span7" id="descripcion" name="descripcion" rows="2" maxlength="1000" style="width: 750px"></textarea> 
                            </div>
                        </div><!-- /clearfix -->
                    </div>


                </div>
                <div class="row show-grid">
                    <div class="span14 offset1">
                        <table table cellpadding="0" cellspacing="0" border="0" class="display" id="alumnos">
                            <thead>
                                <tr>
                                    <th>Cedula</th>
                                    <th>Nombre</th>
                                    <th>Apellido</th>
                                    <th>Observaciones</th>
                                    <th>Nota</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>                                
                            </tbody>

                        </table>
                        <div class="row show-grid">
                            <div class="span4 offset11 ">
                                <button id="inscribir" type="submit" class="btn primary icon alternative edit"  >Agregar Notas</button>
                            </div>
                        </div>
                    </div>
                </div>

            </fieldset>
        </form>
        <a href="javascript:window.history.back();">&laquo; Volver </a>
    </div>
    <div class="row show-grid">
        <div class="span8 offset1">
            <?php if (isset($this->pudoAgregar) && $this->pudoAgregar != false) : ?>
                <div class="alert-message success" id="add-ok" >
                    <a class="close" href="#" onclick="javascript:$('add-ok').fade(); return false;">×</a>
                    <p align="center">Se han agregado las notas</p>
                    </br>                    
                </div>
            <?php endif; ?>

            <?php if (isset($this->pudoAgregar) && $this->pudoAgregar == false) : ?>
                <div class="alert-message error" id="add-failed">
                    <a class="close" href="#" onclick="javascript:$('add-failed').fade(); return false;">×</a>
                    <p>Error, no se han podido ingresar las notas</p>
                </div>
            <?php endif; ?>
        </div>
    </div>
</div>
