<!doctype html>
<?php
$session = new \Zend_Session_Namespace();
$session->username = 'none';
?>
<html>
    <head>
        <meta charset="utf-8">

        <title>SGTi</title>
        <meta name="description" content="">
        <meta name="author" content="MouserTech">
        <!-- iconos de pagina -->
        <link rel="shortcut icon" href="/img/ti.gif">
        <link rel="apple-touch-icon" href="/img/ti.gif">
        <link rel="apple-touch-icon" sizes="72x72" href="/img/ti.gif">
        <link rel="apple-touch-icon" sizes="114x114" href="/img/ti.gif">
        <!-- iconos de pagina --> 
        <link href="/css/bootstrap/bootstrap.css" rel="stylesheet">
        <link rel="stylesheet/less" href="/css/bootstrap/lib/bootstrap_xtra.less">
        <script src="/css/bootstrap/js/less.js"></script>
        <script src="/js/jquery/jquery-1.7.1.js" type="text/javascript"></script>
        <?php
        /* 
        <script src="/js/scriptaculous/prototype.js" type="text/javascript"></script>
        <script src="/js/scriptaculous/scriptaculous.js?load=effects" type="text/javascript"></script>
         */
        ?>
        <script src="/js/ajax_functions.js" type="text/javascript"></script>

        <style type="text/css">
            body {
                padding-top: 60px;
            }
        </style>

    </head>
    <body>
        <div class="topbar">
            <div class="topbar-inner">
                <div class="container-fluid">
                    <a class="brand" href="/index">SGTi</a>
                    <ul class="nav">
                        <?php
                        if (Zend_Auth::getInstance()->hasIdentity()) {
                            $rol = Zend_Auth::getInstance()->getIdentity()->getRol();
                            ?>
                            <li class="<?php echo ($session->main_tab_location == 0) ? 'active' : ''; ?>">
                                <a href="/index">Inicio</a>
                            </li>
                            <? if ($rol == 'alumno' || $rol == 'alumno_docente') { ?>
                                <li class="<?php echo ($session->main_tab_location == 1) ? 'active' : ''; ?>">
                                    <a href="/alumnos/verperfil">Alumnos</a>
                                </li>
                            <? } ?>
                            <? if ($rol == 'docente' || $rol == 'alumno_docente' || $rol == 'administrativo_docente') { ?>
                                <li class="<?php echo ($session->main_tab_location == 2) ? 'active' : ''; ?>">
                                    <a href="/docentes/pasarlista">Docentes</a>
                                </li>
                            <? } ?>
                            <? if ($rol == 'administrativo' || $rol == 'administrativo_docente') { ?>
                                <li class="<?php echo ($session->main_tab_location == 3) ? 'active' : ''; ?>">
                                    <a href="/administracion/adminplanestudio">Administracion</a>
                                </li>
                            <? } ?>
                            <li class="<?php echo ($session->main_tab_location == 6) ? 'active' : ''; ?>" >
                                <a href="/material/mainmaterial">Material</a>
                            </li>
                            <li class="<?php echo ($session->main_tab_location == 5) ? 'active' : ''; ?>" >
                                <a href="/index/info">Info</a>
                            </li>
                        <?php } ?>
                    </ul>
                    <?php
                    if (Zend_Auth::getInstance()->hasIdentity()) :
                        $usuario = Zend_Auth::getInstance()->getIdentity();
                        ?><div class="span9 pull-right">
                            <button class="span3 pull-right btn danger icon alternative remove" onclick="window.location.href='/seguridad/logout'" style="margin-top: 5px;">Cerrar Sesion</button>
                            <h5   style="color: white; padding-right: 5px;" > Bienvenido, <a> <?php echo $usuario->getPersona()->getNombre() . " " . $usuario->getPersona()->getApellido() . '   '; ?></a></h5>
                        </div>    
                    <?php else : ?>
                        <div class="pull-right">
                            <button class="btn primary icon alternative arrowright" onclick="window.location.href='/seguridad/login'" style="margin-top: 5px;">Login</button>
                        </div>
                    <?php endif; ?>                 
                </div>
            </div>
        </div>


        <div class="content">
            <div class="row show-grid">        
                <div class="span16" style="padding-left: 20px">   
                    <?php echo $this->layout()->content; ?>
                    <footer>
                        <p>&copy;  <?php
                    $copyYear = 2012;
                    $curYear = date('Y');
                    echo $copyYear . (($copyYear != $curYear) ? '-' . $curYear : '');
                    ?>
                            MouserTech - All Rights Reserved
                        </p>
                    </footer>
                </div>
            </div>    
        </div> 
    </body>
</html>
