<?php
$session = new Zend_Session_Namespace();
$session->admin_tab_location = 2;
include("tabBar.php");
include("dataTables.php");
?>


<div class="span16">
    <h2>Administracion Docentes</h2>
    <br>        
    <button class="btn primary icon alternative add" onclick="window.location.href='/administracion/agregardocente'">Agregar Docente</button>&nbsp;
   
<br>
<div class="span12">
<table table cellpadding="0" cellspacing="0" border="0" class="display" id="docentes">
    <thead>
        <tr>
            <th>Cedula</th>
            <th>Nombre</th>
            <th>Apellido</th>
        </tr>
    </thead>
    <tbody>      
	<?php foreach($this->listadocentes as $docente) :?>
            <tr class="even gradeA" onclick="window.location.href='/administracion/infodocente/id/<?php echo $docente->getId(); ?>'">
            <td class="center"><?php echo $docente->getCi();?></td>
            <td class="center"><?php echo $docente->getNombre();?></td>
            <td class="center"><?php echo $docente->getApellido();?></td>	
            
            </tr>     
        <?php endforeach; ?>  
    </tbody>
    
</table>
</div>
<script type="text/javascript" charset="utf-8">
    $(document).ready(function() {
        $('#docentes').dataTable({
        "bPaginate": true,
        //bLengthChange muestra un combo para seleccionar cuantas entradas se quieren mostrar en pantalla
        "bLengthChange": false,
        "bFilter": true,
        "bSort": true,
        "bInfo": true,
        "bAutoWidth": false,
        "aaSorting": [[ 1, "asc" ]],
        "sScrollY": "250px",
        "bPaginate": false,
        "oLanguage": {
            "sLengthMenu": "Mostrar _MENU_ filas por pagina",
            "sZeroRecords": "No hay registros",
            "sInfo": "Mostrando _START_ a _END_ de _TOTAL_ registros",
            "sInfoEmpty": "Mostrando 0 a 0 de 0 registros",
            "sInfoFiltered": "(filtered from _MAX_ total records)",
            "sSearch":"Buscar por:"
                  }
    } );
    } );
</script>
</div>