<?php include("tabBar.php"); ?>
<div class="row show-grid">
<div class="span10 offset1">

 <h2>Agregar Materia a Periodo <a href="/administracion/infoperiodo/idperiodo/<?php echo $this->selectedPeriodo->getId(); ?>"><?php echo $this->selectedPeriodo->getNumero(); ?></a> de Plan <a href="/administracion/infoplan/id/<?php echo $this->selectedPeriodo->getPlanDeEstudio()->getId(); ?>"><?php echo $this->selectedPeriodo->getPlanDeEstudio()->getNombre(); ?>  </a></h2>

    
    <form action="#" method="post">
        <fieldset>
           

            <div class=" <?php echo (!is_null($this->errors) && array_key_exists('nombre', $this->errors)) ? 'clearfix error' : 'clearfix'; ?> ">
                <label for="nombre">Nombre</label>    
                <div class="input">
                    <input class="xlarge" id="xlInput" name="nombre" maxlength="50" type="text" value="<?php echo $this->form->getValue('nombre'); ?>"  /> 
                    <?php if (!is_null($this->errors) && array_key_exists('nombre', $this->errors)) : ?>
                        <br>
                        <br>
                        <span class="help-inline">Debe ingresar un nombre válido (solo letras)</span>
                    <?php endif; ?>
                    <br/>
                </div>
            </div><!-- /clearfix -->

            <div class=" <?php echo (!is_null($this->errors) && array_key_exists('creditos', $this->errors)) ? 'clearfix error' : 'clearfix'; ?> ">
                <label for="creditos">Creditos</label>    
                <div class="input">
                    <input class="span2" id="xlInput" name="creditos" maxlength="25" type="text" value="<?php echo $this->form->getValue('creditos'); ?>"  /> 
                    <?php if (!is_null($this->errors) && array_key_exists('creditos', $this->errors)) : ?>
                        <br>
                        <br>
                        <span class="help-inline">Debe ingresar creditos válidos (solo numeros)</span>
                    <?php endif; ?>
                    <br/>
                </div>
            </div><!-- /clearfix -->            

            <div class=" <?php echo (!is_null($this->errors) && array_key_exists('tipoAprobacion', $this->errors)) ? 'clearfix error' : 'clearfix'; ?> ">
                <label for="tipoAprobacion">Tipo Aprobacion</label>    
                <div class="input">
                    <select name="tipoAprobacion" id="tipoAprobacion" >
                        <?php $sel = (strcmp($this->form->getValue('tipoAprobacion'), "proyecto") == 0) ? "<option value=proyecto selected>Por Proyecto</option>" : "<option value='proyecto'>Por Proyecto</option>"; ?>
                        <option value="parcial">Por Parcial</option>
                        <?php echo $sel ?>
                    </select>
                    <?php if (!is_null($this->errors) && array_key_exists('tipoAprobacion', $this->errors)) : ?>
                        <br>
                        <br>
                        <span class="help-inline">Siempre va a haber uno elejido</span>
                    <?php endif; ?>
                    <br/>
        </fieldset>        
            <!-- /clearfix -->
        </fieldset>
        <?php if ($this->errors != null) { ?>      
            <div class="clearfix error">
                <span class="help-inline">Se han encontrado errores en el formulario, por favor complete todos los campos correctamente</span>
            </div><!-- /clearfix -->
        <?php } ?>
        <div class="row show-grid">
            <div class="span4 offset6"><button class="btn primary icon alternative add" type="submit">Agregar</button></div>
        </div>

    </form>

    <?php if (isset($this->pudoAgregar) && $this->pudoAgregar == true) : ?>
        <div class="alert-message success" id="add-ok">
            <a class="close" href="#" onclick="javascript:$('add-ok').fade(); return false;">×</a>
            <center><p>La <a class="success" href="#" onclick="window.location.href='/administracion/infomateria/idmateria/<?php echo $this->pudoAgregar; ?>'">Materia</a> ha sido agregada correctamente.</p> </center>
            </br>
            <center><a class="success" href="#" onclick="window.location.href='/administracion/agregarcurso/idmateria/<?php echo $this->pudoAgregar; ?>'">Click aqui para agregar Curso a Materia</a></center>
        </div>
    <?php endif; ?>

    <?php if (isset($this->pudoAgregar) && $this->pudoAgregar == false) : ?>
        <div class="alert-message error" id="add-failed">
            <a class="close" href="#" onclick="javascript:$('add-failed').fade(); return false;">×</a>
            <p>La materia no ha sido agregada.</p>
        </div>
    <?php endif; ?>
    <a href="javascript:window.history.back();">&laquo; Volver </a>
</div>
</div>

