<?php include("tabBar.php"); ?>

<div class="span12">

    <?php print_r($this->success); ?>
    <h2>Crear Curso de Materia  <a href="/administracion/infomateria/idmateria/<?php echo $this->materia->getId(); ?>"><?php echo $this->materia->getNombre(); ?></a> </h2>

    <form action="#" method="post">
        <fieldset>

            <div class=" <?php echo (!is_null($this->errors) && array_key_exists('anio', $this->errors)) ? 'clearfix error' : 'clearfix'; ?> ">
                <label for="anio">A&ntilde;o del Curso</label>     
                <div class="input">
                    <input class="xlarge" id="anio" name="anio" maxlength="4" type="text" value="<?php echo $this->form->getValue('anio'); ?>"/> 
                    <?php if (!is_null($this->errors) && array_key_exists('anio', $this->errors)) : ?>
                        <span class="help-inline">*</span>
                    <?php endif; ?>
                    <br/>
                </div>
            </div><!-- /clearfix -->
            <div class="row show-grid">
                <div class="span4 offset6"><button class="btn primary icon alternative add" type="submit">Agregar</button></div>
            </div>
        </fieldset>
    </form>

    <?php if ($this->errors != null) : ?>      
        <div class="clearfix error">
            <span class="help-inline">Se han encontrado errores en el formulario, por favor complete todos los campos correctamente</span>
        </div><!-- /clearfix -->
    <?php endif; ?>


    <div class="row show-grid">
        <div class="span8 offset1">

            <?php if (isset($this->pudoAgregar) && $this->pudoAgregar == true) : ?>
                <div class="alert-message success" id="add-ok" >
                    <a class="close" href="#" onclick="javascript:$('add-ok').fade(); return false;">×</a>
                    <p align="center">
                        El 
                        <a href="/administracion/infocurso/cursoid/<?php echo $this->pudoAgregar; ?>"> <u><b> curso</b></u></a>
                        ha sido agregado correctamente.
                    </p>
                </div>
            <?php endif; ?>

            <?php if (isset($this->pudoAgregar) && $this->pudoAgregar == false) : ?>
                <div class="alert-message error" id="add-failed">
                    <a class="close" href="#" onclick="javascript:$('add-failed').fade(); return false;">×</a>
                    <p>El curso no ha sido agregado.</p>
                </div>
            <?php endif; ?>
        </div>
    </div>
    <a href="javascript:window.history.back();">&laquo; Volver </a>
</div>
