<?php include("tabBar.php"); ?>

<div class="span16">
    <script src="http://code.jquery.com/jquery-1.7.min.js"></script>
    <script src="/js/bootstrap-datepicker.js"></script>
    
    <div class="row show-grid">
        <div class="span16">
            <form action="#" method="post">
                <fieldset>
                    <div class="row">
                        <div class="span8">
                            <legend>Ingresar Alumno</legend>
                            </br></br>
                            <div class=" <?php echo (!is_null($this->errors) && array_key_exists('ci', $this->errors)) ? 'clearfix error' : 'clearfix'; ?> ">
                                <label for="ci">Cédula <a>*</a></label>    
                                <div class="input">
                                    <input class="xlarge" id="xlInput" name="ci" maxlength="8" type="text" value="<?php echo $this->form->getValue('ci'); ?>"/> 
                                    <?php if (!is_null($this->errors) && array_key_exists('ci', $this->errors)) : ?>
                                        <br/>
                                        <br/>                
                                        <span class="help-inline">Debe ingresar una Ci valida (solo numeros)</span>
                                    <?php endif; ?>
                                    <br/>
                                </div>
                            </div><!-- /clearfix -->

                            <div class=" <?php echo (!is_null($this->errors) && array_key_exists('nombre', $this->errors)) ? 'clearfix error' : 'clearfix'; ?> ">
                                <label for="nombre">Nombre <a>*</a></label>  
                                <div class="input">
                                    <input  class="xlarge" id="xlInput" name="nombre" maxlength="60" type="text" value="<?php echo $this->form->getValue('nombre'); ?>"/> 
                                    <?php if (!is_null($this->errors) && array_key_exists('nombre', $this->errors)) : ?>
                                        <span class="help-inline">Debe ingresar un nombre válido (solo letras)</span>
                                    <?php endif; ?>
                                    <br/>
                                </div>
                            </div><!-- /clearfix -->

                            <div class=" <?php echo (!is_null($this->errors) && array_key_exists('apellido', $this->errors)) ? 'clearfix error' : 'clearfix'; ?> ">
                                <label for="apellido">Apellido <a>*</a></label>    
                                <div class="input">
                                    <input  class="xlarge" id="xlInput" name="apellido" maxlength="60" type="text" value="<?php echo $this->form->getValue('apellido'); ?>"/> 
                                    <?php if (!is_null($this->errors) && array_key_exists('apellido', $this->errors)) : ?>
                                        <br/>
                                        <br/>
                                        <span class="help-inline">Debe ingresar un apellido válido (solo letras)</span>
                                    <?php endif; ?>
                                    <br/>
                                </div>
                            </div><!-- /clearfix -->

                            <div class=" <?php echo (!is_null($this->errors) && array_key_exists('fechaNac', $this->errors)) ? 'clearfix error' : 'clearfix'; ?> ">
                                <label for="fechaNac">Fecha Nacimiento <a>*</a></label>    
                                <div class="input">
                                    <input data-datepicker="datepicker" name="fechaNac" class="small" type="text" readonly style="cursor:default;" value="<?php echo $this->form->getValue('fechaNac'); ?>"/>
                                    <?php if (!is_null($this->errors) && array_key_exists('fechaNac', $this->errors)) : ?>
                                        <span class="help-inline">Debe seleccionar una fecha</span>
                                    <?php endif; ?>
                                    <br/>
                                </div>
                            </div><!-- /clearfix -->

                            <div class=" <?php echo (!is_null($this->errors) && array_key_exists('telefono', $this->errors)) ? 'clearfix error' : 'clearfix'; ?> ">
                                <label for="telefono">Telefono</label>    
                                <div class="input">
                                    <input  class="xlarge" id="xlInput" name="telefono" maxlength="15" type="text" value="<?php echo $this->form->getValue('telefono'); ?>" /> 
                                    <?php if (!is_null($this->errors) && array_key_exists('telefono', $this->errors)) : ?>
                                        <br/>
                                        <br/>
                                        <span class="help-inline">Debe ingresar un telefono válido (solo numeros)</span>
                                    <?php endif; ?>
                                    <br/>
                                </div>
                            </div><!-- /clearfix -->

                            <div class=" <?php echo (!is_null($this->errors) && array_key_exists('celular', $this->errors)) ? 'clearfix error' : 'clearfix'; ?> ">
                                <label for="celular">Celular</label>    
                                <div class="input">
                                    <input  class="xlarge" id="xlInput" name="celular" maxlength="9" type="text" value="<?php echo $this->form->getValue('celular'); ?>" /> 
                                    <?php if (!is_null($this->errors) && array_key_exists('celular', $this->errors)) : ?>
                                        <br/>
                                        <br/>
                                        <span class="help-inline">Debe ingresar un celular válido (solo numeros)</span>
                                    <?php endif; ?>
                                    <br/>
                                </div>
                            </div><!-- /clearfix -->

                            <div class=" <?php echo (!is_null($this->errors) && array_key_exists('localidad', $this->errors)) ? 'clearfix error' : 'clearfix'; ?> ">
                                <label for="localidad">Localidad</label>    
                                <div class="input">
                                    <input   class="xlarge" id="xlInput" name="localidad" maxlength="60" type="text" value="<?php echo $this->form->getValue('localidad'); ?>" /> 
                                    <?php if (!is_null($this->errors) && array_key_exists('localidad', $this->errors)) : ?>
                                        <br/>
                                        <br/>
                                        <span class="help-inline">Debe ingresar una localidad válida (solo letras)</span>
                                    <?php endif; ?>
                                    <br/>
                                </div>
                            </div><!-- /clearfix -->


                            <div class=" <?php echo (!is_null($this->errors) && array_key_exists('mail', $this->errors)) ? 'clearfix error' : 'clearfix'; ?> ">
                                <label for="mail">Mail <a>*</a></label>    
                                <div class="input">
                                    <input   class="xlarge" id="xlInput" name="mail" maxlength="60" type="text"  value="<?php echo $this->form->getValue('mail'); ?>"/> 
                                    <?php if (!is_null($this->errors) && array_key_exists('mail', $this->errors)) : ?>
                                        <br/>
                                        <br/>
                                        <br/>
                                        <span class="help-inline">Debe ingresar un mail válido (solo letras)</span>
                                    <?php endif; ?>
                                    <br/>
                                </div>
                            </div><!-- /clearfix -->
                        </div> 

                        <div class="span8">
                            <div class="well" >
                                <h3>Requisitos:</h3>
                                <div class="clearfix">
                                    <!-- /clearfix -->
                                    <div class="input">
                                        <ul class="inputs-list">
                                            <li>
                                                <label>
                                                    <input type="checkbox" name="cedula" value="cond1"/>
                                                    <span>Fotocopia de Cedula de Identidad</span>

                                                </label>
                                            </li>
                                            <li>
                                                <label>
                                                    <input type="checkbox" name="carne" value="cond2"/>
                                                    <span>Carnet de Salud Vigente</span>
                                                </label>
                                            </li>
                                            <li>
                                                <label>
                                                    <input type="checkbox" name="foto" value="cond3"/>
                                                    <span>Foto tipo Carné</span>
                                                </label>
                                            </li>
                                            <li>
                                                <label>
                                                    <input type="checkbox" name="pase" value="cond4"/>
                                                    <span>Pase Secundaria (Formula 69-A) o pase de UTU con Bachillerato Tecnologico aprobado (verificado por R.E. UTU)</span>
                                                </label>
                                            </li>

                                        </ul>
                                        <span class="help-block">
                                            <strong>Nota:</strong> Hasta que el alumno no cumpla todos los requisitos no se podra generar la inscripcion.
                                        </span>
                                    </div>
                                </div> 
                            </div> 
                            <div class="row show-grid">
                                <div class="span5  offset6">
                                    <button class="btn primary icon alternative add" type="submit">Agregar</button>
                                </div>
                            </div>
                            </br></br></br>
                            <?php if (isset($this->pudoAgregar) && $this->pudoAgregar != false) : ?>
                                <div class="alert-message success" id="add-ok">
                                    <a class="close" href="#" onclick="javascript:$('add-ok').fade(); return false;">×</a>
                                    
                                    <p style="text-align:center;">El alumno ha sido agregado correctamente.</p>
                                    <center><a href="/administracion/agregaralumno/descargar/1/id/<?php echo $this->pudoAgregar?>/req/<?php echo $this->req[0];echo $this->req[1];echo $this->req[2];echo $this->req[3];?>">Haga click para descargar control de inscripcion</a></center>
                                </div>
                            <?php endif; ?>

                            <?php if (isset($this->pudoAgregar) && $this->pudoAgregar == false) : ?>
                                <div class="alert-message error" id="add-failed">   
                                    <a class="close" href="#" onclick="javascript:$('add-failed').fade(); return false;">×</a>
                                    <p>El alumno no ha sido agregado.</p>
                                </div>
                            <?php endif; ?>
                            <?php if ($this->errors != null) : ?>      
                                <div class="row show-grid">
                                    <div class="span5 offset2">    
                                        <div class="clearfix error">
                                            <span class="help-inline">Se han encontrado errores en el formulario, por favor complete todos los campos correctamente</span>
                                        </div><!-- /clearfix -->
                                    </div>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>  
                </fieldset>
            </form>
        </div>
        <a href="javascript:window.history.back();">&laquo; Volver </a>
    </div>  
    
    <!--Este script cambia el formato de l a fecha a dia mes y año si la quieren de otra forma solamente hay q comentar el script y queda normal -->
    <script>
        $.extend($.fn.datepicker.defaults, {
            parse: function (string) {
                var matches;
                if ((matches = string.match(/^(\d{2,2})\/(\d{2,2})\/(\d{4,4})$/))) {
                    return new Date(matches[3], matches[1] - 1, matches[2]);
                } else {
                    return null;
                }
            },
            format: function (date) {
                var
                month = (date.getMonth() + 1).toString(),
                dom = date.getDate().toString();
                if (month.length === 1) {
                    month = "0" + month;
                }
                if (dom.length === 1) {
                    dom = "0" + dom;
                }
                return dom + "-" + month + "-" + date.getFullYear();
            }
        });  
    </script>