<?php
include("tabBar.php");
include("dataTables.php");
?>

<h1>Info Rol: <?php echo($this->selectedRol->getNombre()); ?></h1>
<div class="span12">
        <div class='clearfix'>
            <label for="nombre">Nombre: <?php echo($this->selectedRol->getNombre()); ?> </label>    
            

            <div class='clearfix'>
                <label for="descripcion">Descripcion: <?php echo($this->selectedRol->getDescripcion()); ?></label>    
              
       </div>
            
        <table table cellpadding="0" cellspacing="0" border="0" class="display" id="roles">
    <thead>
        <tr>
            <th> Permiso </th>
            <th>Permitido</th>
        </tr>
        
    </thead>    
        </div>
        

