<?php
include("tabBar.php");
include("dataTables.php");
?>
<div class="row show-grid">
    <div class="span16">

        <div class="row">
            <div class="span9">
                <h2>Crear Evento Calificacion</h2>
                </br>
                <form action="#" method="post">
                    <fieldset>

                        <div class="clearfix ">
                            <label for="anio">Tipo de Evento Calificacion</label>  </br>   
                            <div class="input">
                                <input class="span5" id="eventoCalificacion" name="eventoCalificacion" maxlength="30" type="text" value="<?php //echo $this->form->getValue('anio');             ?>"/> 

                                <br/>
                            </div>
                        </div><!-- /clearfix -->
                        <br/><br/>
                        <div class="row show-grid">
                            <div class="span4 offset6"><button class="btn primary icon alternative add" type="submit">Agregar</button></div>
                        </div>
                    </fieldset>
                </form>
            </div>

            <div class="span7"> 
                </br></br>
                <h3>Eventos Calificacion Existentes</h3>
                <table table cellpadding="0" cellspacing="0" border="0" class="display" id="eventos">
                    <thead>
                        <tr>
                            <th>Evento Calificacion</th>
			    <th></th>
                        </tr>
                    </thead>
                    <tbody>
			<?php foreach ($this->listaTipos as $tipo) : ?>
    			<tr class="even gradeA" onclick="window.location.href='/administracion/eliminartipocal/id/<?php echo $tipo->getId(); ?>'">
    			    <td class="center"><?php echo $tipo->getNombre(); ?></td>
			    <td class="center"><button type="button" id="editar" class="span1 btn danger icon alternative remove" onclick="window.location.href='/administracion/eliminartipocal/id/<?php echo $tipo->getId(); ?>'" ></button></td>
    			</tr>     
			<?php endforeach; ?> 
                    </tbody>
                </table>

                <script type="text/javascript" charset="utf-8">
  
                    $(document).ready(function() {
                        $('#eventos').dataTable({
                            "bPaginate": true,
                            //bLengthChange muestra un combo para seleccionar cuantas entradas se quieren mostrar en pantalla
                            "bLengthChange": false,
                            "bFilter": true,
                            "bSort": true,
                            "bInfo": true,
                            "bAutoWidth": false,
                            "aaSorting": [[ 0, "desc" ]],
                            "sScrollY": "220px",
                            "bPaginate": false,
                            "oLanguage": {
                                "sLengthMenu": "Mostrar _MENU_ filas por pagina",
                                "sZeroRecords": "No hay registros",
                                "sInfo": "Mostrando _START_ a _END_ de _TOTAL_ registros",
                                "sInfoEmpty": "Mostrando 0 a 0 de 0 registros",
                                "sInfoFiltered": "(filtered from _MAX_ total records)",
                                "sSearch":"Buscar por:"
                            },
			    "aoColumns" : [
					     { sWidth: '35%' },
					    { sWidth: '7%' }
					    ]
                        } );
                    } );
                </script>
            </div>
        </div>

        <a href="javascript:window.history.back();">&laquo; Volver </a>
    </div>
</div>



