<?php
$session = new Zend_Session_Namespace();
$session->admin_tab_location = 1;
include("tabBar.php");
include("dataTables.php");
?>

<script type="text/javascript">
    function activateInputs(){         
        document.getElementById("tipo").removeAttribute('readonly');
        document.getElementById("numero").removeAttribute('readonly');
        document.getElementById("modificar").disabled=false;
        document.getElementById("editar").disabled=true;
    }   
    function deactivateInputs(){         
        document.getElementById("tipo").readOnly =true;
        document.getElementById("numero").readOnly =true;
        document.getElementById("modificar").disabled=true;
        document.getElementById("editar").disabled=false;
    } 
</script>

<div class="row show-grid">
    <div class="span16 offset1">
        <div class="row">
            <h2>Info Periodo: <?php echo $this->form->getValue('numero'); ?>     - Plan <a href="/administracion/infoplan/planid/<?php echo $this->selectedPeriodo->getPlanDeEstudio()->getId(); ?>"><?php echo $this->selectedPeriodo->getPlanDeEstudio()->getNombre(); ?></a> </h2>
            <div class="span7">
                <br>        
                <br>
                <form action="#" method="post">
                    <fieldset>
                        <div class=" clearfix">
                            <label for="numero">Numero: &nbsp;</label>
                            <div class="input">
                                <input class="span4" id="numero" name="numero" maxlength="25" readonly type="text" value="<?php echo $this->form->getValue('numero'); ?>"/> 
                            </div>
                        </div><!-- /clearfix -->
                        </br>
                        <div class=" clearfix">
                            <label for="tipo">Tipo: &nbsp;</label> 
                            <div class="input">
                                <input class="span2"  id="tipo" name="tipo" maxlength="25" type="text"readonly value="<?php echo $this->form->getValue('tipo'); ?>"/> 
                            </div>
                        </div><!-- /clearfix -->                                                
                        </br></br>
                        <div class="row show-grid">
                            <div class="span2 offset2">
                                <button type="button" id="editar" class="btn primary icon alternative edit" onclick="javascript:activateInputs();" >Editar</button>
                            </div>
                            <div class="span3">
                                <button id="modificar" disabled="true" type="submit" class="btn primary icon alternative add" onclick="javascript:activateInputs();" >Modificar</button>
                            </div>
                        </div>

                    </fieldset>
                </form>
            </div>
            <div class="span9"><br>             
                <h3>Materias</h3>

                <table table cellpadding="0" cellspacing="0" border="0" class="display" id="planes">
                    <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Creditos</th>                            
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->selectedPeriodo->getMaterias() as $materia) { ?>
                            <tr class="even gradeA"   onclick="window.location.href='/administracion/infomateria/idmateria/<?php echo $materia->getId(); ?>'">
                                <td class="center"><?php echo $materia->getNombre(); ?></td>
                                <td class="center"><?php echo $materia->getCreditos(); ?></td>                                
                            </tr>
                        <?php } ?>
                    </tbody>

                </table>

                <div class="row show-grid">
                    <div class="span3 offset6">    
                        <button class="btn primary icon alternative add" onclick="window.location.href='/administracion/agregarmateria/perid/<?php echo ($this->selectedPeriodo->getId()); ?>'">Agregar Materia</button>&nbsp;
                    </div>
                </div>

                <script type="text/javascript" charset="utf-8">
  
                    $(document).ready(function() {
                        $('#planes').dataTable({
                            "bPaginate": true,
                            //bLengthChange muestra un combo para seleccionar cuantas entradas se quieren mostrar en pantalla
                            "bLengthChange": false,
                            "bFilter": true,
                            "bSort": true,
                            "bInfo": true,
                            "bAutoWidth": false,
                            "aaSorting": [[ 1, "asc" ]],
                            "sScrollY": "200px",
                            "bPaginate": false,
                            "oLanguage": {
                                "sLengthMenu": "Mostrar _MENU_ filas por pagina",
                                "sZeroRecords": "No hay registros",
                                "sInfo": "Mostrando _START_ a _END_ de _TOTAL_ registros",
                                "sInfoEmpty": "Mostrando 0 a 0 de 0 registros",
                                "sInfoFiltered": "(filtered from _MAX_ total records)",
                                "sSearch":"Buscar por:"
                            },
                            "aoColumns" : [
                                { sWidth: '50%' },
                                { sWidth: '25%' }
                            ] 
                        } );
                    } );
                </script>
            </div>
        </div>
        <a href="/administracion/infoplan/planid/<?php echo $this->selectedPeriodo->getPlanDeEstudio()->getId(); ?>">&laquo; Volver </a>
    </div> 

</div>