<?php
include("tabBar.php");
include("dataTables.php");
?>
<div class="span9 offset1">
    <h3>Info Clase</h3>
    <form action="#" method="post">
        <fieldset>
            <div class="row show-grid">
                <div class="span4">
                    <div class="clearfix">
                        <label>Curso:&nbsp;</label> 
                        <div class="input">
                            <input class="span3" readonly id="curso" name="curso" type="text" value="<?php echo $this->selectedCurso->getMateria()->getNombre()." - ".$this->selectedCurso->getAnio(); ?>"/> 
                        </div>
                    </div><!-- /clearfix -->
                    <div class="clearfix">
                        <label for="fecha">Fecha</label>    
                        <div class="input">
                            <input class="span3" readonly id="curso" name="curso" type="text" value="<?php echo $this->selectedClase->getFecha()->format('d-m-Y'); ?>"/> 
                        </div>
                    </div><!-- /clearfix -->
                </div>
                <table table cellpadding="0" cellspacing="0" border="0" class="display" id="alumnos">
                    <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Apellido</th>
                            <th>Cedula</th>
                            <th>Asistio?</th>
                        </tr>
                    </thead>
                    <tbody>
			<?php foreach ($this->selectedClase->getAsistencias() as $asistencia) : ?>
			    <tr class="even gradeA">				
				<td class="center"><?php echo $asistencia->getAlumno()->getNombre(); ?></td>
				<td class="center"><?php echo $asistencia->getAlumno()->getApellido(); ?></td>
				<td class="center"><?php echo $asistencia->getAlumno()->getCi(); ?></td>				
				<td class="center"><?php echo $asistencia->getAsistio(); ?></td>	    
			    </tr>
			<?php endforeach; ?> 
                    </tbody>	    
                </table>
        </fieldset>
    </form>
    <a href="javascript:window.history.back();">&laquo; Volver </a>
</div>

<script type="text/javascript" charset="utf-8">
    $(document).ready(function() {
	$('#alumnos').dataTable({
	    "bPaginate": true,
	    //bLengthChange muestra un combo para seleccionar cuantas entradas se quieren mostrar en pantalla
	    "bLengthChange": false,
	    "bFilter": true,
	    "bSort": true,
	    "bInfo": true,
	    "bAutoWidth": false,
	    "aaSorting": [[ 1, "asc" ]],
	    "sScrollY": "200px",
	    "bPaginate": false,
	    "oLanguage": {
		"sLengthMenu": "Mostrar _MENU_ filas por pagina",
		"sZeroRecords": "No hay registros",
		"sInfo": "Mostrando _START_ a _END_ de _TOTAL_ registros",
		"sInfoEmpty": "Mostrando 0 a 0 de 0 registros",
		"sInfoFiltered": "(filtered from _MAX_ total records)",
		"sSearch":"Buscar por:"
	    },
	    "aoColumns" : [
		{ sWidth: '30%' },
		{ sWidth: '30%' },
		{ sWidth: '30%' },
		{ sWidth: '5%' }

	    ] 
	} );
    } );
</script>