<?php
include("tabBar.php");
include("dataTables.php");
?>
<script src="/js/modal.js"></script>
<script src="/js/bootstrap-datepicker.js"></script>

<script type="text/javascript">
    function activateInputs(){ 
        document.getElementById("nombre").removeAttribute('readonly');
        document.getElementById("ci").removeAttribute('readonly');
        document.getElementById("apellido").removeAttribute('readonly');
        document.getElementById("fechaNac").removeAttribute('readonly');
        document.getElementById("telefono").removeAttribute('readonly');
        document.getElementById("celular").removeAttribute('readonly');
        document.getElementById("localidad").removeAttribute('readonly');
        document.getElementById("mail").removeAttribute('readonly');
        document.getElementById("modificar").disabled=false;
        document.getElementById("editar").disabled=true;
      
        
    }   
    function deactivateInputs(){ 
        document.getElementById("nombre").readOnly =true;
        document.getElementById("ci").readOnly =true;
        document.getElementById("apellido").readOnly =true;
        document.getElementById("fechaNac").readOnly =true;
        document.getElementById("telefono").readOnly =true;
        document.getElementById("celular").readOnly =true;
        document.getElementById("localidad").readOnly =true;
        document.getElementById("mail").readOnly =true;
        document.getElementById("modificar").disabled=true;
        document.getElementById("editar").disabled=false;
    } 
</script>





<div class="row show-grid">
    <div class="span16">
        <h1>Info Docente</h1>
        <div class="row">
            <div class="span8">
                <form action="#" method="post">
                    <fieldset>
                        <div class=" <?php echo (!is_null($this->errors) && array_key_exists('ci', $this->errors)) ? 'clearfix error' : 'clearfix'; ?> ">
                            <label for="ci">Cedula</label>    
                            <div class="input">
                                <input class="xlarge" id="ci" name="ci" maxlength="8" readonly type="text" value="<?php echo $this->form->getValue('ci'); ?>"/> 
                                <?php if (!is_null($this->errors) && array_key_exists('ci', $this->errors)) : ?>
                                    <span class="help-inline">*</span>
                                <?php endif; ?>
                                <br/>
                            </div>
                        </div><!-- /clearfix -->

                        <div class=" <?php echo (!is_null($this->errors) && array_key_exists('nombre', $this->errors)) ? 'clearfix error' : 'clearfix'; ?> ">
                            <label for="nombre">Nombre</label>    
                            <div class="input">
                                <input  class="xlarge" id="nombre" name="nombre" maxlength="60" readonly type="text" value="<?php echo $this->form->getValue('nombre'); ?>"/> 
                                <?php if (!is_null($this->errors) && array_key_exists('nombre', $this->errors)) : ?>
                                    <span class="help-inline">*</span>
                                <?php endif; ?>
                                <br/>
                            </div>
                        </div><!-- /clearfix -->

                        <div class=" <?php echo (!is_null($this->errors) && array_key_exists('apellido', $this->errors)) ? 'clearfix error' : 'clearfix'; ?> ">
                            <label for="apellido">Apellido</label>    
                            <div class="input">
                                <input  class="xlarge" id="apellido" name="apellido" maxlength="60" readonly type="text" value="<?php echo $this->form->getValue('apellido'); ?>"/> 
                                <?php if (!is_null($this->errors) && array_key_exists('apellido', $this->errors)) : ?>
                                    <span class="help-inline">*</span>
                                <?php endif; ?>
                                <br/>
                            </div>
                        </div><!-- /clearfix -->

                        <div class=" <?php echo (!is_null($this->errors) && array_key_exists('fechaNac', $this->errors)) ? 'clearfix error' : 'clearfix'; ?> ">
                            <label for="fechaNac">Fecha Nacimiento</label>    
                            <div class="input">
                                <input data-datepicker="datepicker" id="fechaNac"  name="fechaNac" class="small" readonly type="text" value="<?php echo $this->form->getValue('fechaNac'); ?>"/>
                                <?php if (!is_null($this->errors) && array_key_exists('fechaNac', $this->errors)) : ?>  
                                    <span class="help-inline">*</span>
                                <?php endif; ?>
                                <br/>
                            </div>
                        </div><!-- /clearfix -->

                        <div class=" <?php echo (!is_null($this->errors) && array_key_exists('telefono', $this->errors)) ? 'clearfix error' : 'clearfix'; ?> ">
                            <label for="telefono">Telefono</label>    
                            <div class="input">
                                <input  class="xlarge" id="telefono" name="telefono" maxlength="15" readonly type="text" value="<?php echo $this->form->getValue('telefono'); ?>"/> 
                                <?php if (!is_null($this->errors) && array_key_exists('telefono', $this->errors)) : ?>
                                    <span class="help-inline">*</span>
                                <?php endif; ?>
                                <br/>
                            </div>
                        </div><!-- /clearfix -->

                        <div class=" <?php echo (!is_null($this->errors) && array_key_exists('celular', $this->errors)) ? 'clearfix error' : 'clearfix'; ?> ">
                            <label for="celular">Celular</label>    
                            <div class="input">
                                <input  class="xlarge" id="celular" name="celular" maxlength="9" readonly  type="text"  value="<?php echo $this->form->getValue('celular'); ?>"/> 
                                <?php if (!is_null($this->errors) && array_key_exists('celular', $this->errors)) : ?>
                                    <span class="help-inline">*</span>
                                <?php endif; ?>
                                <br/>
                            </div>
                        </div><!-- /clearfix -->

                        <div class=" <?php echo (!is_null($this->errors) && array_key_exists('localidad', $this->errors)) ? 'clearfix error' : 'clearfix'; ?> ">
                            <label for="localidad">Localidad</label>    
                            <div class="input">
                                <input   class="xlarge" id="localidad" name="localidad" maxlength="60" readonly type="text" value="<?php echo $this->form->getValue('localidad'); ?>"/> 
                                <?php if (!is_null($this->errors) && array_key_exists('localidad', $this->errors)) : ?>
                                    <span class="help-inline">*</span>
                                <?php endif; ?>
                                <br/>
                            </div>
                        </div><!-- /clearfix -->


                        <div class=" <?php echo (!is_null($this->errors) && array_key_exists('mail', $this->errors)) ? 'clearfix error' : 'clearfix'; ?> ">
                            <label for="mail">Mail</label>    
                            <div class="input">
                                <input   class="xlarge" id="mail" name="mail" maxlength="60" type="text" readonly  value="<?php echo $this->form->getValue('mail'); ?>"/> 
                                <?php if (!is_null($this->errors) && array_key_exists('mail', $this->errors)) : ?>
                                    <span class="help-inline">*</span>
                                <?php endif; ?>
                                <br/>
                            </div>
                        </div><!-- /clearfix -->
                        <div class="row show-grid">
                            <div class="span2 offset2">
                                <button type="button" id="editar" class="btn primary icon alternative edit" onclick="javascript:activateInputs();" >Editar</button>
                            </div>
                            <div class="span3">
                                <button id="modificar" disabled="true" type="submit" class="btn primary icon alternative add" onclick="javascript:activateInputs();">Modificar</button>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
            <div class="span8">
                <div class="row show-grid">
                    </br></br></br></br>
                    <div class="span4 ">
                        <button class="btn primary icon alternative mail" type="submit" onclick="window.location.href='/administracion/enviarmail/mails/<?php echo ($this->selectedDocente->getMail()); ?>'">Enviar Mail</button>
                    </div> 
                    </br> </br>
                    <div class="span5 ">
                        <button class="btn primary icon alternative log" onclick="window.location.href='/administracion/agregardocenteacurso/docenteid/<?php echo ($this->selectedDocente->getId()); ?>'">Asociar a Curso</button>&nbsp;
                    </div>
                    </br> </br>
                    <div class="span5 ">
                        <button class="btn primary icon alternative edit" type="submit" onclick="window.location.href='/administracion/cambiarcontrasena/personaid/<?php echo ($this->selectedDocente->getId()); ?>'">Cambiar Contraseña</button>
                    </div>
                    </br> </br>
                    <div class="span3 ">
                        <a class="btn danger icon alternative remove" data-controls-modal="eliminar" data-backdrop="static" >Eliminar</a>
                    </div>
                </div>
                <?php if ($this->errors != null) { ?>      
                    <div class="row show-grid">
                        <div class="span5">    
                            <div class="clearfix error">
                                <span class="help-inline">Se han encontrado errores en el formulario, por favor complete todos los campos correctamente</span>
                            </div><!-- /clearfix -->
                        </div>
                    </div>
                <?php } ?>
            </div>
        </div>
        <a href="javascript:window.history.back();">&laquo; Volver </a>
    </div>  
</div>   

<script type="text/javascript" charset="utf-8">
    $.extend($.fn.datepicker.defaults, {
        parse: function (string) {
            var matches;
            if ((matches = string.match(/^(\d{2,2})\/(\d{2,2})\/(\d{4,4})$/))) {
                return new Date(matches[3], matches[1] - 1, matches[2]);
            } else {
                return null;
            }
        },
        format: function (date) {
            var
            month = (date.getMonth() + 1).toString(),
            dom = date.getDate().toString();
            if (month.length === 1) {
                month = "0" + month;
            }
            if (dom.length === 1) {
                dom = "0" + dom;
            }
            return dom + "-" + month + "-" + date.getFullYear();
        }
    });
</script>

<!-- ///////////////  Modal para Eliminar   /////////////////-->

<div id="eliminar" class="modal hide fade">
    <div class="modal-header">
        <a href="#" class="close">&times;</a>
        <h3>Eliminar Docente</h3>
    </div>
    <div class="modal-body">
        <p>Esta seguro que desea eliminar a <?php echo $this->form->getValue('nombre') . ' ' . $this->form->getValue('apellido'); ?></p>
    </div>
    <div class="modal-footer">
        <button class="btn danger icon alternative remove" onclick="window.location.href='/administracion/eliminardocente/id/<?php echo ($this->selectedDocente->getId()); ?>'">Eliminar</button>
        <a type="button" id="editar" class="btn secondary" data-controls-modal="eliminar" data-backdrop="static" onclick="javascript:$('#eliminar').modal('close');" >Cancelar</a>
    </div>
</div>
<!-- ///////////////  Modal para Eliminar   /////////////////-->


