<?php
include("tabBar.php");
include("dataTables.php");
?>

<?php //echo($this->selectedCurso->getNombre()); ?>
<div class="row show-grid">
    <div class="span16 offset1">
        <div class="span11">
            <h2>Info Curso: <?php echo $this->selectedCurso->getAnio(); ?> - <a href="/administracion/infomateria/idmateria/<?php echo $this->selectedCurso->getMateria()->getId(); ?>"><?php echo $this->selectedCurso->getMateria()->getNombre(); ?></a>&nbsp;&nbsp;&nbsp;&nbsp; Clases y Horas</h2>
        </div>
        </br>
        <div class="row show-grid">
            <button class="span4 btn primary icon alternative " onclick="window.location.href='/administracion/infocurso/cursoid/<?php echo ($this->selectedCurso->getId()); ?>'">Alumnos - Eventos Calificacion</button>&nbsp;
            <button class="span4 btn primary icon alternative " onclick="window.location.href='/administracion/infocursod/cursoid/<?php echo ($this->selectedCurso->getId()); ?>'">Docentes</button>
        </div>
        </br>
        <div class="row">
            <div class="span7">
                <h3>Clases</h3>
                <table table cellpadding="0" cellspacing="0" border="0" class="display" id="clases">
                    <thead>
                        <tr>
                            <th>Fecha</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->selectedCurso->getClases() as $clase) : ?>
                            <tr class="even gradeA" onclick="window.location.href='/administracion/infoclase/claseid/<?php echo $clase->getId(); ?>/cursoid/<?php echo $this->selectedCurso->getId(); ?>'">
                                <td class="center"><?php echo $clase->getFecha()->format('d-m-Y'); ?></td>
                            </tr>     
                        <?php endforeach; ?>      
                    </tbody>

                </table>
                <script type="text/javascript" charset="utf-8">
                    $(document).ready(function() {
                        $('#clases').dataTable({
                            "bPaginate": true,
                            //bLengthChange muestra un combo para seleccionar cuantas entradas se quieren mostrar en pantalla
                            "bLengthChange": false,
                            "bFilter": true,
                            "bSort": true,
                            "bInfo": true,
                            "bAutoWidth": false,
                            "aaSorting": [[ 1, "asc" ]],
                            "sScrollY": "220px",
                            "bPaginate": false,
                            "oLanguage": {
                                "sLengthMenu": "Mostrar _MENU_ filas por pagina",
                                "sZeroRecords": "No hay registros",
                                "sInfo": "Mostrando _START_ a _END_ de _TOTAL_ registros",
                                "sInfoEmpty": "Mostrando 0 a 0 de 0 registros",
                                "sInfoFiltered": "(filtered from _MAX_ total records)",
                                "sSearch":"Buscar por:"
                            }
                        } );
                    } );
                </script></div>

            <div class="span7 offset1">            
                <h3>Horas</h3>
                <table table cellpadding="0" cellspacing="0" border="0" class="display" id="horas">
                    <thead>
                        <tr>
                            <th>Salon</th>
                            <th>Dia</th>
                            <th>Hora Inicio</th>
                            <th>Hora Fin</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->listahorarios as $horario) : ?>
                            <tr class="even gradeA" onclick="window.location.href='/administracion/modificarhorario/horarioid/<?php echo $horario->getId(); ?>'">
                                <td class="center"><?php echo $horario->getSalon()->getNombre(); ?></td>
                                <td class="center"><?php echo $horario->getDia(); ?></td>
                                <td class="center"><?php echo $horario->getHoraInicio()->format('H:i:s'); ?></td>
                                <td class="center"><?php echo $horario->getHoraFin()->format('H:i:s'); ?></td>
                            </tr>     
                        <?php endforeach; ?> 
                    </tbody>

                </table>
                <div class="row show-grid">
                    <div class="span3 offset5">    
                        <button class="btn primary icon alternative edit" onclick="window.location.href='/administracion/agregarhorario/idcurso/<?php echo ($this->selectedCurso->getId()); ?>'">Agregar Horario</button>&nbsp;
                    </div>
                </div>
                <script type="text/javascript" charset="utf-8">
  
                    $(document).ready(function() {
                        $('#horas').dataTable({
                            "bPaginate": true,
                            //bLengthChange muestra un combo para seleccionar cuantas entradas se quieren mostrar en pantalla
                            "bLengthChange": false,
                            "bFilter": true,
                            "bSort": true,
                            "bInfo": true,
                            "bAutoWidth": false,
                            "aaSorting": [[ 1, "asc" ]],
                            "sScrollY": "220px",
                            "bPaginate": false,
                            "oLanguage": {
                                "sLengthMenu": "Mostrar _MENU_ filas por pagina",
                                "sZeroRecords": "No hay registros",
                                "sInfo": "Mostrando _START_ a _END_ de _TOTAL_ registros",
                                "sInfoEmpty": "Mostrando 0 a 0 de 0 registros",
                                "sInfoFiltered": "(filtered from _MAX_ total records)",
                                "sSearch":"Buscar por:"
                            }
                        } );
                    } );
                </script>
            </div>
        </div>
        <a href="javascript:window.history.back();">&laquo; Volver </a>
    </div>
</div>
