<?php
$session = new Zend_Session_Namespace();
include("tabBar.php");
include("dataTables.php");
?>

<div class="span16">
    <h2>Administracion Noticias</h2>
    <br>        
    <button class="btn primary icon alternative add" onclick="window.location.href='/administracion/agregarnoticia'">Agregar Noticia</button><br><br>
    <table table cellpadding="0" cellspacing="0" border="0" class="display" id="noticias">
        <thead>
            <tr>
                
                <th>Fecha</th>
                <th>Titulo</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->listanoticias as $noticia) : ?>
                <tr class="even gradeA" >
                    <td class="center"><?php echo $noticia->getUltimaActualizacion()->format('m-d-Y'); ?></td> 
                    <td class="center"><?php echo $noticia->getTitulo(); ?></td>
                    <td class="center"><button type="button" id="editar" class="span1 btn primary icon alternative edit" onclick="window.location.href='/administracion/modificarnoticia/noticiaid/<?php echo $noticia->getId(); ?>'"></button>&nbsp&nbsp<button type="button" id="editar" class="span1 btn danger icon alternative remove" onclick="window.location.href='/administracion/eliminarnoticia/id/<?php echo ($noticia->getId()); ?>'" ></button></td>
                </tr>     
            <?php endforeach; ?>  
        </tbody>
    </table>
    </br></br>
    <a href="javascript:window.history.back();">&laquo; Volver </a>
</div>
<script type="text/javascript" charset="utf-8">
    $(document).ready(function() {
        $('#noticias').dataTable({
            "bPaginate": true,
            //bLengthChange muestra un combo para seleccionar cuantas entradas se quieren mostrar en pantalla
            "bLengthChange": false,
            "bFilter": true,
            "bSort": true,
            "bInfo": true,
            "bAutoWidth": false,
            "aaSorting": [[ 0, "desc" ]],
            "sScrollY": "250px",
            "bPaginate": false,
            "oLanguage": {
                "sLengthMenu": "Mostrar _MENU_ filas por pagina",
                "sZeroRecords": "No hay registros",
                "sInfo": "Mostrando _START_ a _END_ de _TOTAL_ registros",
                "sInfoEmpty": "Mostrando 0 a 0 de 0 registros",
                "sInfoFiltered": "(filtered from _MAX_ total records)",
                "sSearch":"Buscar por:"
            },
            "aoColumns" : [
                                 { sWidth: '12%' },
                                { sWidth: '70%' },
                                { sWidth: '15%' }
                            ] 
        } );
    } );
</script>
