<?php
$session = new \Zend_Session_Namespace();
include("tabBar.php");
include("dataTables.php");
?>

<meta http-equiv="content-type" content="text/html; charset=utf-8" />





<div class="span12">
    <form action="#" method="post">
         <input class="xlarge" id="descargar" name="descargar" type="hidden" value="descargar"/>
         <input class="xlarge" id="idalumno" name="idalumno" type="hidden" value="<?php $this->idalumno;?>"/>
         <div class="span4 offset6"><button class="btn primary icon alternative add" type="submit">Descargar</button></div>
    </form>
    
</div>

