<?php
$session = new \Zend_Session_Namespace();
include("tabBar.php");
include("dataTables.php");
?>

<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<div class="row show-grid">
    <div class="span16 offset1">

        <h2>Asistencias</h2>

        <div class="span12">
            <table table cellpadding="0" cellspacing="0" border="0" class="display" id="asistencias">
                <thead>
                    <tr>
                        <th>Fecha</th>
                        <th>Asistio?</th>
                    </tr>
                </thead>
                <tbody>
		    <?php foreach ($this->listaAsistencias as $asistencia) : ?>
			<tr class="even gradeA">
			    <td class="center"><?php echo $asistencia['fecha'];?></td>
			    <td class="center"><?php echo $asistencia['asistio'];?></td>	    
			</tr>     
		    <?php endforeach; ?>      
		</tbody>

            </table>
            </br> 
            </br>

        </div>
        <a href="javascript:window.history.back();">&laquo; Volver </a>
    </div>

</div>
<script type="text/javascript" charset="utf-8">
    $(document).ready(function() {
        $('#asistencias').dataTable({
            "bPaginate": true,
            //bLengthChange muestra un combo para seleccionar cuantas entradas se quieren mostrar en pantalla
            "bLengthChange": false,
            "bFilter": true,
            "bSort": true,
            "bInfo": true,
            "bAutoWidth": false,
            "aaSorting": [[ 1, "asc" ]],
            "sScrollY": "250px",
            "bPaginate": false,
            "oLanguage": {
                "sLengthMenu": "Mostrar _MENU_ filas por pagina",
                "sZeroRecords": "No hay registros",
                "sInfo": "Mostrando _START_ a _END_ de _TOTAL_ registros",
                "sInfoEmpty": "Mostrando 0 a 0 de 0 registros",
                "sInfoFiltered": "(filtered from _MAX_ total records)",
                "sSearch":"Buscar por:"
            }
        } );
    } );
</script>